export const LOGIN_SCENE = 'LOGIN_SCENE';
export const INTERACTION_SELECT_AREA_SCENE = 'INTERACTION_SELECT_AREA_SCENE';
export const INTERACTION_ADD_AREA_SCENE = 'INTERACTION_ADD_AREA_SCENE';
export const INTERACTION_SELECT_CONTAINER_SCENE =
  'INTERACTION_SELECT_CONTAINER_SCENE';
export const INTERACTION_ADD_CONTAINER_SCENE =
  'INTERACTION_ADD_CONTAINER_SCENE';
