export enum InteractionActionsEnum {
  REVERT_INTERACTION = 'REVERT',
  SHOW_CONTAINER = 'SHOW-AC',
  RETURN_TO_MAIN_MENU = 'MAIN-MENU',
  SUBSCRIBE_MORE = 'SUB-MORE',
  UNSUBSCRIBE_MORE = 'UNSUB-MORE',
}
