import {
  GET_MY_AREAS_TEXT,
  SHOW_ALL_AREAS_TEXT,
  SUBSCRIBE_AREA_TEXT,
  UNSUBSCRIBE_AREA_TEXT,
} from '../constants/menu';

export enum InteractionAreaEnum {
  INTERACTION_AREA_SUBSCRIBE = SUBSCRIBE_AREA_TEXT,
  INTERACTION_AREA_UNSUBSCRIBE = UNSUBSCRIBE_AREA_TEXT,
  INTERACTION_SHOW = SHOW_ALL_AREAS_TEXT,
  INTERACTION_SHOW_SUBSCRIBED_AREAS = GET_MY_AREAS_TEXT,
}
