import {
  GET_MY_CONTAINERS_TEXT,
  SHOW_ALL_CONTAINERS_TEXT,
  SUBSCRIBE_CONTAINER_TEXT,
  UNSUBSCRIBE_CONTAINER_TEXT,
} from '../constants/menu';

export enum InteractionContainerEnum {
  INTERACTION_CONTAINER_SUBSCRIBE = SUBSCRIBE_CONTAINER_TEXT,
  INTERACTION_CONTAINER_UNSUBSCRIBE = UNSUBSCRIBE_CONTAINER_TEXT,
  INTERACTION_SHOW_AREA_CONTAINERS = SHOW_ALL_CONTAINERS_TEXT,
  INTERACTION_SHOW_SUBSCRIBED_CONTAINERS = GET_MY_CONTAINERS_TEXT,
}
